### ISSUE TITLE
Fix memory leak / infinite run-time on simulator nodes

### ISSUE THREAD

**Issue by ghost** [zrdev/zrdev.github.io#15]
Some simulation threads are not stopped when done; run ps -ef | grep java on a simulator to see. Could be due to infinite loops in the user code, maybe? Killing them normally doesn't work; you have to kill -9 or shut down the whole JVM.

**Comment by alvarso** [comment]
Also from Jake:

> I didn't seen obvious timeout on the simulation execution.  I might have
> missed it, but it seems like the executors run the command line program,
> then check the time it took to run afterward to determine if it timed out.
> That won't work if the process just hangs forever.

**Comment by mizanul** [comment]
I did run svn update on maven main project and then deployed zr-simulation-threadpool-1.4-1.4.0-SNAPSHOT.jar on QA and then started simulator.  I get the following error:

Caused by: javax.persistence.PersistenceException: [PersistenceUnit: ZeroRoboticsPU] Unable to build EntityManagerFactory
    at org.hibernate.ejb.Ejb3Configuration.buildEntityManagerFactory(Ejb3Configuration.java:915)
    at org.hibernate.ejb.Ejb3Configuration.buildEntityManagerFactory(Ejb3Configuration.java:890)
    at org.hibernate.ejb.HibernatePersistence.createContainerEntityManagerFactory(HibernatePersistence.java:74)
    at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:288)
    at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:310)
    at edu.mit.ssl.zerorobotics.Configuration.DatabaseConfig.entityManagerFactoryBean(DatabaseConfig.java:57)
    at edu.mit.ssl.zerorobotics.Configuration.DatabaseConfig$$EnhancerByCGLIB$$f658fc45.CGLIB$entityManagerFactoryBean$0(<generated>)
    at edu.mit.ssl.zerorobotics.Configuration.DatabaseConfig$$EnhancerByCGLIB$$f658fc45$$FastClassByCGLIB$$1b688fdb.invoke(<generated>)
    at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
    at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:286)
    at edu.mit.ssl.zerorobotics.Configuration.DatabaseConfig$$EnhancerByCGLIB$$f658fc45.entityManagerFactoryBean(<generated>)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:160)
    ... 40 more
Caused by: org.hibernate.AnnotationException: mappedBy reference an unknown target entity property: edu.mit.ssl.zerorobotics.database.dao.model.TournamentsRank.team_id in edu.mit.ssl.zerorobotics.database.dao.model.TournamentsTeam.tournamentsRankCollection
    at org.hibernate.cfg.annotations.CollectionBinder.bindStarToManySecondPass(CollectionBinder.java:705)
    at org.hibernate.cfg.annotations.CollectionBinder$1.secondPass(CollectionBinder.java:665)
    at org.hibernate.cfg.CollectionSecondPass.doSecondPass(CollectionSecondPass.java:66)
    at org.hibernate.cfg.Configuration.originalSecondPassCompile(Configuration.java:1591)
    at org.hibernate.cfg.Configuration.secondPassCompile(Configuration.java:1366)
    at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1731)
    at org.hibernate.ejb.EntityManagerFactoryImpl.<init>(EntityManagerFactoryImpl.java:94)
    at org.hibernate.ejb.Ejb3Configuration.buildEntityManagerFactory(Ejb3Configuration.java:905)
    ... 55 more

Looks like I do not have the latest code of the zr-database-library-1.4.  Please check-in all code. I need to test my memory leak code.

**Comment by mizanul** [comment]
Anyway,  I have temporarily modified the edu.mit.ssl.zerorobotics.database.dao.model.TournamentsRank.java file to continue my test.
changed from teamId to team_id

**Comment by mizanul** [comment]
Changing from from teamId to team_id in edu.mit.ssl.zerorobotics.database.dao.model.TournamentsRank.java file fixed the error.

**Comment by mizanul** [comment]
Based on Jakes comment:
I had a watcher for the process, which kills the process if it exceeds certain time.  During my development unit test it interfered with the thread-pool.  So, I turned that off. Now, I am going re-implement that very carefully, so that my thread-pool code works as it was.

**Comment by mizanul** [comment]
Created edu.mit.ssl.zerorobotics.concurrent.KillProcessWatchdog and updated SimulateFromRequestRunnable.jva file as follows:
  KillProcessWatchdog processWatchDog = new KillProcessWatchdog(processTimeout);

```
    final CommandLine cmd = CommandLine.parse("java -Xms64m -Xmx256m -cp " + ZRConstants.getInstance().getRemoteProcessExtraClasspath() + ":" + obtainClassPath() + "  " + edu.mit.ssl.zerorobotics.compilesimulation.simulation.FarmSimulationAfterCompile.class.getName() + " " + cfg.getSimId());
    final DefaultExecutor executor = new DefaultExecutor();
    executor.setExitValue(0);
    executor.setWatchdog(processWatchDog);
    executor.setWorkingDirectory(new File(workingDirectory)); 
```

**Comment by mizanul** [comment]
Also added ZRUtilites file in the zr-simulation-library project as a common utility file for all other simulation related projects.  All utility related code will be moved from other files to this file.

**Comment by mizanul** [comment]
deployed memory leak fix in QA and PROD
